steps:
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'gs://trendai-envvars/.env.$BRANCH_NAME', '.env']

  - name: 'gcr.io/$PROJECT_ID/dep'
    args: ['ensure', '-v']
    env:
    - 'GOPATH=/gopath'
    - 'PROJECT_ROOT=github.com/trend-ai/TrendAI_backend'
    volumes:
    - name: 'go'
      path: '/gopath'

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "app.yml"]
    env:
      - 'GOPATH=/gopath'
    volumes:
    - name: 'go'
      path: '/gopath'

timeout: "1600s"
