steps:
  - name: gcr.io/cloud-builders/gsutil
    args: ['cp', 'gs://trendai-envvars/.env.$BRANCH_NAME', '.env']

  - name: 'gcr.io/$PROJECT_ID/dep'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "==> List of directories before run dep"
        ls
        echo "==> Running dep ensure"
        dep ensure -v
        echo "==> List of directories after run dep"
        ls
    env:
    - 'GOPATH='
    - 'PROJECT_ROOT=github.com/trend-ai/TrendAI_backend'

  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy", "app.yml"]
    env:
      - 'GOPATH=/builder/home/go'

timeout: "1600s"
